import SiteHeader from '../components/SiteHeader'
import SiteFooter from '../components/SiteFooter'

export default function TermsPage() {
  return (
    <>
      <SiteHeader />
      <main className="bg-royal-blue-900 min-h-screen">
        <section className="px-6 lg:px-8 py-24">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
            <p className="text-gray-500 text-sm mb-12">Last updated: July 2026</p>

            <div className="space-y-10 text-gray-300 leading-relaxed">
              <div>
                <h2 className="text-xl font-semibold text-white mb-3">1. Using the service</h2>
                <p>
                  By creating an account, you agree to use LABEELE.AI only for lawful purposes and
                  not to abuse, overload, or attempt to circumvent rate limits or access controls
                  on the service.
                </p>
              </div>
              <div>
                <h2 className="text-xl font-semibold text-white mb-3">2. Accounts</h2>
                <p>
                  You&apos;re responsible for keeping your account credentials secure and for
                  activity that happens under your account. Let us know right away if you suspect
                  unauthorized access.
                </p>
              </div>
              <div>
                <h2 className="text-xl font-semibold text-white mb-3">3. Plans and billing</h2>
                <p>
                  Paid plans are billed on the cycle shown at signup. You can cancel at any time;
                  your access continues until the end of the current billing period.
                </p>
              </div>
              <div>
                <h2 className="text-xl font-semibold text-white mb-3">4. Responses from specialist agents</h2>
                <p>
                  Responses are generated by an AI model and are provided for informational
                  purposes. Review AI-generated guidance &mdash; especially security, infrastructure,
                  or code recommendations &mdash; before acting on it in production systems.
                </p>
              </div>
              <div>
                <h2 className="text-xl font-semibold text-white mb-3">5. Termination</h2>
                <p>
                  You may delete your account at any time from account settings. We may suspend
                  accounts that violate these terms.
                </p>
              </div>
              <div>
                <h2 className="text-xl font-semibold text-white mb-3">6. Contact</h2>
                <p>
                  Questions about these terms can be sent to{' '}
                  <a href="mailto:legal@labeele.ai" className="text-gold-500 hover:text-gold-400">
                    legal@labeele.ai
                  </a>
                  .
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <SiteFooter />
    </>
  )
}
